services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: wattiodb
      POSTGRES_USER: wattio
      POSTGRES_PASSWORD: wattio
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data:cached
  backend:
    build:
      context: .
      dockerfile: Dockerfile.yaml
    command: python /backend/app/main.py
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql://wattio:wattio@postgres:5432/wattiodb"
    depends_on:
      - "postgres"
    ports:
      - 8000:8000

volumes:
  db_data:
